### ISSUE TITLE
GKE templates versionning and config to a private repo

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#12]
GKE templates are not versioned or backuped currently, let's make sure they are,

**Comment by jaseemabid** [comment]
@chmouel +1 to this. Great if we can write some scripts to completely automate this. Ansible maybe?

**Comment by chmouel** [comment]
I think a bash script would suffice in this case, (it's just need something like kubectl get all > backup.yaml;git commit -am "blah" *yaml)) but if there is need for something more complex then sure ansible should be the way!

This ticket address only backup as for recovery that may be a all different topic to discuss (as is this needed to be automated?)

**Comment by jaseemabid** [comment]
@chmouel Shall we start this for next sprint? 

I mention this specifically because this task will kind of make out service transparent; we should document the service that actually runs on service. 

For example, I had a hard time today trying to find the diff b/w 2 services.

**Comment by pradeepto** [comment]
Closing as obsolete. Yay!
