### ISSUE TITLE
Jenkins Stats - Build time stats

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#15]
Jenkins Statistics and Usage monitoring is a large topics,

There is a lot of different topic around providing resources monitoring, stats and others for Jenkins. 
This card here is only first to try to provide a timing stat on build time, to store somewhere how long does it take for each build to be built. It would be great if this can be done in a (i.e: sqlite) database so we can easily provide report out of it.

This may need to have an external (and protected) service with an API to be built to upload the stats to.

We need currently for https://jenkins.cd.test.fabric8.io/

Let's try to keep it as simple as possible at first, the most important purpose of this issue is to figure out how we do collection and store it somewhere, we will get into the more complex to investigate how to integrate with  osio other generic tools etc... in the next phase.

**Comment by chmouel** [comment]
@sthaha maybe something to look at next,

**Comment by jaseemabid** [comment]
xref https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/133

**Comment by piyush-garg** [comment]
GKE has been shut down. Closing this.
