### ISSUE TITLE
Review user permissions from jamess and Rob on github and others

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#2]
Go over on repos and others and see if we have to remove those permissions,

**Comment by pradeepto** [comment]
@chmouel I don't think we should remove their permissions. After the stuff is Open Source. Just review them and see if they are very permissive (admin etc).

**Comment by chmouel** [comment]
yep only to remove the admin access! thanks for pointing,

**Comment by chmouel** [comment]
@rupalibehera has removed the jamess access to jenkins,
