### ISSUE TITLE
Liveness/readiness probes for the slave images

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#21]
If we could check at the slave node's end if it is connected to master _reliably_ with a script (`$ am-i-connected-to-master.sh`), then we can rely on some of the k8s fundamentals to monitor the health of the instances without using any external services.

I expect this approach to work well in the future when we run this Jenkins images inside the osio environment as well. 

See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes for docs.

**Comment by piyush-garg** [comment]
we are not needing this anymore.
