### ISSUE TITLE
Document various images

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#25]
Already in progress at https://github.com/fabric8io/fabric8-build-team/wiki/Jenkins-Images. 

- [ ] What are the different images we use?
- [ ] How are they built? 
- [ ] How are they deployed
- [ ] Document the versions of software running on it. For example, planner folks were asking for the node.js version and we didn't have a place to point them to. 

Using this issue to track progress.

**Comment by jaseemabid** [comment]
@rupalibehera bump!

**Comment by pradeepto** [comment]
Closing as obsolete.
