### ISSUE TITLE
Investigate Fabric8_CI vs fabric8 Jenkins folders on test.cd.fabric8.io

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#27]
Fabric8_CI seems to be for  `vertx-maven-plugin|fabric8-platform|gofabric8|pipeline-test-project|kubernetes-model|almighty-core|exposecontroller` and fabric8io for `^(?!^fabric8-planner$|^fabric8-online-docs$|^keycloak-deployment$|^fabric8-ui$|^fabric8-team-components$|^openshift-jenkins-s2i-config$|^fabric8-online$|^fabric8-init-tenant$).*`.

Investigate and understand why we need 2 and why its configured differently.

**Comment by piyush-garg** [comment]
we have shut down GKE. closing this.
