### ISSUE TITLE
Build output is very often missing

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#30]
I've seen this all the time with other builds but now this happened with gofabric8. This is a good isolated test case for us to debug because it's just our code and the command is just a `make`.

 There is some output for the `make` in the second build, but the first one produced nothing at all.

https://jenkins.cd.test.fabric8.io/job/fabric8_CI/job/gofabric8/job/PR-642/2/console
https://jenkins.cd.test.fabric8.io/job/fabric8_CI/job/gofabric8/job/PR-642/2/console

**Comment by jaseemabid** [comment]
https://jenkins.cd.test.fabric8.io/job/fabric8io/job/fabric8-maven-plugin/job/master/22/consoleFull 

This build of fmp master is potentially losing output because the log line does not indicate any error but the command indeed failed. This might be worse than initially thought.

**Comment by chmouel** [comment]
We should generally report bugs on openshift.io org if you deem to think it's important to notify it, cc @pradeepto

**Comment by piyush-garg** [comment]
we are not anymore maintaining gofabric8. Closing this.
