### ISSUE TITLE
Investigate @Library import of fabric8-pipeline-library

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#33]
1. Every other plugin is baked into the instance, this should be too. 
2. Adds a constant overhead to every build by pulling this library from github
3. ^ is also responsible for a lot more log noise
4. Importing master makes it hard for us to make breaking changes/releases
5. If users change the version from master to something else, we will have different versions in production at the same time. Probably not a good idea. 
6. An extra line in the Jenkinsfile - that's one extra thing for our customers to understand. 
7. Our build story need not revolve around this single library unless required.

**Comment by piyush-garg** [comment]
Closing this, as we moved to the new pipeline.
