### ISSUE TITLE
`npm install` fails with Z_BUF_ERROR

### ISSUE THREAD

**Issue by maxandersen** [fabric8io/fabric8-build-team#38]
https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/view/change-requests/job/PR-2291/ failed with 

```
`npm install` fails with Z_BUF_ERROR
```

looks like issue in node where suggested fix is to move to 8.9.

see https://github.com/npm/npm/issues/11993

**Comment by jaseemabid** [comment]
@maxandersen Do you think every tenant using the same version of the image makes sense? If this happens to our customers and if they are on a platform like travis, they can update the dependency on their own and fix the problem without waiting for us to update the version and fix the issue (and possibly break builds for other people). 

I'll get a PR for this in the meanwhile.

**Comment by jaseemabid** [comment]
@maxandersen https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/13

**Comment by maxandersen** [comment]
on travis users don't control the base image that runs what corresponds to their "jenkins".

for te build pods users shuold have control what it runs on.

**Comment by piyush-garg** [comment]
we have shut down GKE. closing this.
