### ISSUE TITLE
Jenkins monitoring : GKE / Service Hosted instances

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#4]
Monitoring the fabric8 Jenkins instance. The Jenkins master gets rebooted often, perhaps under load. Before we make any assumptions, we need to set up some kind of monitoring for this instance so that we can take an educated call on what needs to be done.

@jaseemabid @rupalib (helping out with testing and deploying the image)

Now we've no idea about the health and up time of the Jenkins instances. 

1. Add monitoring. Show relevant metrcics. 
2. Restart on failures.

References : 

https://github.com/fabric8-services/fabric8-wit/blob/master/Dockerfile.deploy#L14-L22

https://github.com/fabric8-services/fabric8-wit/blob/master/wit%2Bpmcd.sh

**Comment by pradeepto** [comment]
@jaseemabid You will have to tallk to @fche and SD team. I have shared the PCP doc by SD team privately.

**Comment by jaseemabid** [comment]
@chmouel  I'm moving my notes to wiki here https://github.com/fabric8io/fabric8-build-team/wiki/Jenkins-Monitoring 

Its still a messy draft for anyone else to understand, but I'll keep updating it as I find more info.

**Comment by chmouel** [comment]
looks good, I think you can even do those fancy GH pages if you wanted something pretty 😆

**Comment by jaseemabid** [comment]
Dabbled with zabbix and some Jenkins scripts. I'm blocked on SD team to give me a working zabbix instance to which I can send data.

**Comment by fche** [comment]
(Please open an issue in the internal dtsd/housekeeping gitlab repo to make formal requests upon the SD group.)

**Comment by jaseemabid** [comment]
@fche Sure. I talked to @aditya-konarde and I believe he is tracking it with an issue already.

**Comment by kbsingh** [comment]
before anyone goes away and does work on this - it would be good to see a recap of the existing monitoring efforts ( ie, the SD run Zabbix and the GKE hosted alerting pieces ).

Afaict, there is no work that needs to be done here beyond a couple of endpoints being added to existing infra.

**Comment by fche** [comment]
AIUI, the work being discussed is exactly the interoperation with SD's zabbix.

**Comment by chmouel** [comment]
I concur with @fche the only plan here is to plug into the existing monitoring infra,

**Comment by kbsingh** [comment]
therefore, as @fche reported earlier, we need this tracked on the SD housekeeping repos privately. There is no action item there to get anything done here.

**Comment by kbsingh** [comment]
@arrfab @bstinsonmhk have done some work here to monitoring ci.centos.org's hosted Jenkins with Zabbix and might have some input here as well.

**Comment by jaseemabid** [comment]
@arrfab @bstinsonmhk Hey could you please point me to any resources/docs that might be available? TIA.

**Comment by bstinsonmhk** [comment]
The Monitoring plugin (https://wiki.jenkins.io/display/JENKINS/Monitoring) just added support for prometheus. 

These are also handy: https://wiki.jenkins.io/display/JENKINS/Monitoring+Scripts

In ci.centos.org (Zabbix) we are monitoring our Jenkins master as part of our general "Linux" hostgroup which is a good baseline for OS metrics.

**Comment by fche** [comment]
Thanks for the referral, @bstinsonmhk.  In a local test, the prometheus data available from this Monitoring plugin is a small fraction of that available from the Metrics plugin (in JSON form) or the Prometheus plugin (in prometheus form).  It seems to include practically nothing about the high level application.

[jenkins-monitoring-javamelody.txt](https://github.com/fabric8io/fabric8-build-team/files/1647051/jenkins-monitoring-javamelody.txt)

Compare with https://github.com/fabric8io/fabric8-build-team/issues/24

**Comment by jaseemabid** [comment]
Updates. 

1. I managed to learn enough Zabbix to understand what is required and setup a [docker-compose.yml](https://gist.github.com/jaseemabid/765ee041f0fb8def0a6f4f2001410b03) to run this locally. There are docs in the gist to get started.

2. Worked with Aditya to add a host/item/trapper on the prod zabbix instance. The host based authorization instead of a username/password kind of makes testing zabbix scripts one step harder. How does this even work because I can spoof the IP to send random data? Is this security by obscurity? 

3. Added zabbix to the Jenkins images. Sent a PR to [add zabbix to the base image](https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/12) and got it landed.

4. Used this base image to build a new s2i image. https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/141

5. Realized the hard way that the local installation with gofabric8 uses a different Jenkins from the prod. Local uses https://github.com/fabric8io/jenkins-docker, which is quite different from the prod version (openshift-jenkins-s2i-config). I did a `oc edit dc jenkins` to run the newer image, but that failed with a lot of random issues. Normally I would have been able to test the image locally, polish this [Jenkinsfile](https://gist.github.com/jaseemabid/765ee041f0fb8def0a6f4f2001410b03#file-jenkinsfile) and run this on prod soon, but now I've to debug why I cannot even run the image locally. 

I was hoping to finish this off and get a basic version up by Friday, but (5) turned out to be an unexpected blocker. I'll post updates soon as I make progress.

**Comment by pradeepto** [comment]
Closing as obsolete. Yay!
