### ISSUE TITLE
Fails with java.io.NotSerializableException

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8io/fabric8-build-team#40]
Build console log - https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2472/14/console

**Comment by jarifibrahim** [comment]
Closing this since the issue was because of malformed braces in my code.

**Comment by jaseemabid** [comment]
@jarifibrahim Can you please link to the patch? Its still such a bad error message from the Jenkins end. This is worthy of a FAQ because its going to be painful to debug for end users.

**Comment by jarifibrahim** [comment]
@jaseemabid I'm not sure if this counts as a patch, but here's the commit that fixed the error https://github.com/fabric8-ui/fabric8-planner/pull/2472/commits/f3b5bbbbd0627b5ce2e53db9b36a7e9c7ca1d4e5

We should parse the `release.groovy` and `Jenkinsfile` for syntax errors before we actually execute it.

**Comment by jaseemabid** [comment]
@jarifibrahim Wish the groovy interpreter used by the CPS plugin just threw a syntax error instead of this. Damn.
