### ISSUE TITLE
Remove the openshift-login-plugin fork by submitting a PR upstream

### ISSUE THREAD

**Issue by sthaha** [fabric8io/fabric8-build-team#44]
Gabe has agreed that if we submit an PR that enables the required behaviour (view -> edit mapping) it will be accepted. So lets 
- [ ] submit a PR upstream
- [ ] get that released
- [ ] Replace the openshift-login-plugin.hpi with the upstream one (plugins.txt)
- [ ] Release
- [ ] Delete the fork

**Comment by chmouel** [comment]
Thanks for filling this up, Would be nice if that checklist gets linked to individual 'upstream' issues,

**Comment by sthaha** [comment]
@chmouel noted. I will break it down when we prioritise this and start working on this. like User story -> sprint-items may be during sprint planning. Creating tasks for this which we wouldn't work right away in the sprint would only clutter the backlog since instead of 1 card we will have to move 5 or 6 cards around.

**Comment by piyush-garg** [comment]
Closing this as moving to upstream is already on priority. Upstream has already provided the feature.
