### ISSUE TITLE
Revisit the automated testing setup for Build

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#45]
### 1. Godog tests for the maven image
I wanted to take a look at the jenkins-godog tests to see if will be of any use to improve the state of testing and it looks like it wont be.

There are only 2 _relevant_ [feature files](https://github.com/fabric8-jenkins/godog-jenkins/tree/master/jenkins/features) and and [one of them](https://github.com/fabric8-jenkins/godog-jenkins/blob/master/jenkins/features/organisation.feature) is completely commented out. Even the default templates godog generates are still there, and nobody deleted or cleaned them up.

And to the best of my understanding, we run just [one test](https://github.com/fabric8-jenkins/godog-jenkins/blob/master/jenkins/features/import.feature#L6) and If that is really the case, this project is not worth digging into. Its much easier to start fresh.

**Comment by chmouel** [comment]
Can you describe a bit more into the issue what do you want to achieve, please.

**Comment by jaseemabid** [comment]
I've added basic tests for maven-bulilder here https://github.com/fabric8io-images/maven-builder/pull/37, which can be merged now. 

Ideally I'd like to expand that to release, deploy and verify that the app is running but that's probably a lot of effort now.

**Comment by piyush-garg** [comment]
We are not using this image anymore, we have moved to upstream. Closing this.
