### ISSUE TITLE
Document how a user can update and test the tenant Jenkins images

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#47]
I've probably explained this a few times on the channel already, time for a wiki.

**Comment by chmouel** [comment]
just a warning, testing the tenant jenkins image on loophole is a bit of a loophole, which is going to be closed sometime soon (i.e: this week) this is the work that @sthaha has been working on,

**Comment by jaseemabid** [comment]
@chmouel Thanks for the heads up. Now we need a way to test tenant image changes reliably and document it somewhere.

**Comment by chmouel** [comment]
yep and that's probably not going to be trivial, (not sure how I can make a sad and disappointed  face reaction on your github comment so describing it in words here). We probably want to make a new issue on our backlog to work on this,

**Comment by piyush-garg** [comment]
We have removed the edit rights from the user. Closing this.
