### ISSUE TITLE
Variable loses value when switching from one node to another

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8io/fabric8-build-team#49]
I'm trying to access the `route` variable inside the `container(ui)` block. It turns out the value is not propagated to the `ui` container from `deployOpenshiftNode`. The `route` variable is empty inside the `ui` container. https://github.com/jarifibrahim/fabric8-planner/blob/6e0c28d0878dc22527ae09ceb858e929d690d74a/Jenkinsfile#L69-L91

The route variable gets it value on https://github.com/jarifibrahim/fabric8-planner/blob/6e0c28d0878dc22527ae09ceb858e929d690d74a/Jenkinsfile#L73
and I'm trying to use it on https://github.com/jarifibrahim/fabric8-planner/blob/6e0c28d0878dc22527ae09ceb858e929d690d74a/Jenkinsfile#L88

I need the route variable value inside the `container(ui)` block to run the planner E2E tests.

**Comment by jarifibrahim** [comment]
@sthaha @jaseemabid Any clue why this is not working? or how should I do this?

**Comment by jaseemabid** [comment]
No idea :/

**Comment by jarifibrahim** [comment]
I'm closing this issue since we no longer need this.
