### ISSUE TITLE
Jenkins Auth and admin scoping

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#5]
Jenkins Auth and admin scoping

Scope out what access a developer get? What happens if the developer is the owner of the PR?
Developer should be able to stop and start his build for his own PR.

The steps need to be documented in a proper manner and shared with all developers using fabric8 jenkins for their CI purposes. A set of developers (leads) need to be trained to make sure the whole process is self-service.

**Comment by pradeepto** [comment]
Closing as obsolete.
