### ISSUE TITLE
Restart Jenkins cluster since the docker builds are failing when building jenkins master image

### ISSUE THREAD

**Issue by sthaha** [fabric8io/fabric8-build-team#50]
Restart Jenkins cluster since the docker builds are failing when building jenkins master image

**Comment by krishnapaparaju** [comment]
@sthaha which Jenkins cluster ?

**Comment by sthaha** [comment]
@krishnapaparaju the jenkins.cd cluster.

**Comment by piyush-garg** [comment]
Close this as we shut down GKE
