### ISSUE TITLE
Fabric8-ui builds failing with unknown oc command

### ISSUE THREAD

**Issue by jiekang** [fabric8io/fabric8-build-team#53]
E.g. 

https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-ui/detail/PR-2759/3/pipeline

fails at running `oc get --all namespaces` shell script with unknown flag --all.

Maybe intention is `oc get --all-namespaces`?

**Comment by jaseemabid** [comment]
Ref https://github.com/fabric8-ui/fabric8-ui/pull/2759

**Comment by jaseemabid** [comment]
@jiekang Sorry for this, looks like I broke the build. You are running the pipeline from a testing brach called 'ssh' and I've pushed a fix which _might_ be sufficient. I'm rerunning the build now.

**Comment by jaseemabid** [comment]
Tracking https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/job/PR-2759/5/

**Comment by jiekang** [comment]
Looks to be fixed. Closing.
