### ISSUE TITLE
Nikhil Thomas Ramp Up : OpenShift 

### ISSUE THREAD

**Issue by pradeepto** [fabric8io/fabric8-build-team#57]

**Comment by nikhil-thomas** [comment]
Completed
Subsystems, Components, and Internals: https://learn.openshift.com/subsystems

**Comment by nikhil-thomas** [comment]
Completed
Kubernetes for the Absolute Beginners - Hands-on: https://www.udemy.com/learn-kubernetes/

I could run a 3 node (ubuntu vms) kubernetes cluster and try out pods, replicasets, deployments, services.

**Comment by pradeepto** [comment]
@nikhil-thomas can you update this issue with the latest status? I believe you are on DO 280 right now?

**Comment by nikhil-thomas** [comment]
Started
ROLE: DO180 Introduction to Containers, Kubernetes, and Red Hat OpenShift
Completed Lab1: on ROLE workstation
Currently working towards lab 2: image building using parent image, adding Security Context Constraints to service accounts etc.

**Comment by nikhil-thomas** [comment]
Started: 14th Jan
ROLE: DO288 Red Hat OpenShift Development
Completed Day1: course and labs

Day2 in progress:
current topics:
image streams,
granting access to a project to image streams from other projectrs
oc adm policy
OpenShift build service

**Comment by nikhil-thomas** [comment]
completed image streams, image registries, build triggers/webhooks
Currently going through S2I image builds

**Comment by nikhil-thomas** [comment]
Took DO288 Red Hat Certified  Specialist in OpenShift Application Development Exam today

**Comment by piyush-garg** [comment]
Closing, as @nikhil-thomas has been moved to tasks.
